from abc import ABC, abstractmethod

from agent_host.models import ConversationTurn


class Store(ABC):
    @abstractmethod
    def namespaced(self, agent: str) -> "Store": ...
    @abstractmethod
    def load_memory(self, chat_id: str) -> list[ConversationTurn]: ...
    @abstractmethod
    def save_memory(self, chat_id: str, turns: list[ConversationTurn]) -> None: ...
    @abstractmethod
    def get_prefs(self, chat_id: str) -> dict: ...
    @abstractmethod
    def set_prefs(self, chat_id: str, prefs: dict) -> None: ...
    @abstractmethod
    def seen(self, key: str) -> bool: ...
    @abstractmethod
    def mark_seen(self, keys: list[str]) -> None: ...
    @abstractmethod
    def record_run(self, meta: dict) -> None: ...
